name: Trigger auto deployment for wwwdeankarlancom

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wwwdeankarlancom-AutoDeployTrigger-112cc9c3-c6e2-490d-abdb-a2994823feaa.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WWWDEANKARLANCOM_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ksmacr.azurecr.io
          registryUsername: ${{ secrets.WWWDEANKARLANCOM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WWWDEANKARLANCOM_REGISTRY_PASSWORD }}
          containerAppName: wwwdeankarlancom
          resourceGroup: KSM_Teaching_RG
          imageToBuild: ksmacr.azurecr.io/wwwdeankarlancom:${{ github.sha }}
          
            

     

