name: Trigger auto deployment for wwwdk

# When this action will be executed
on:
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/wwwdeankarlancom-AutoDeployTrigger-112cc9c3-c6e2-490d-abdb-a2994823feaa.yml'

  # Allow manual trigger 
  workflow_dispatch:

permissions:
  id-token: write
  contents: read      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login with Client Secret
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STRT452SIMDEV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STRT452SIMDEV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STRT452SIMDEV_AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.STRT452SIMDEV_AZURE_CLIENT_SECRET }} 

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ksmacr
      # Build and Push Frontend Docker Image
      - name: Build and Push Website Image
        run: |
          docker build -t ksmacr.azurecr.io/wwwdeankarlancom:${{ github.sha }} ./
          docker push ksmacr.azurecr.io/wwwdeankarlancom:${{ github.sha }}
          
      - name: Deploy Website to Azure Container Apps
        run: |
          az containerapp update \
            --name wwwdeankarlancom \
            --resource-group KSM_Teaching_RG \
            --image ksmacr.azurecr.io/wwwdeankarlancom:${{ github.sha }} 
            
